name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:
jobs:
  build-check:
    runs-on: ubuntu-latest
    env:
      PRODUCTION: "false"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "19.x"
      - name: Install dependencies
        run: npm ci

      - name: Check format and linters
        run: npm run test-all

      - name: Build Project
        run: npm run build
